const pool = require("../db/pool");
const crypto = require("crypto");

function own(req, res) { if (req.user.legajo !== Number(req.params.legajo)) { res.status(403).json({ error: "Acceso no autorizado." }); return false; } return true; }

async function analitico(req, res, next) { try {
  if (!own(req,res)) return; const l=req.user.legajo;
  const [hist,total] = await Promise.all([
    pool.query(`SELECT m.id_materia "idMateria",m.nombre_materia "nombreMateria",m.anio_carrera "anioCarrera",COALESCE(h.estado,'Pendiente') estado,h.nota_final "notaFinal",h.fecha_aprobacion "fechaAprobacion",h.tomo,h.folio,ARRAY(SELECT id_materia_principal FROM correlativa c WHERE c.id_materia_requerida=m.id_materia) desbloquea FROM materia m LEFT JOIN historial_academico h ON h.id_materia=m.id_materia AND h.legajo=$1 ORDER BY m.anio_carrera,m.id_materia`,[l]),
    pool.query(`SELECT (SELECT count(*) FROM materia) total,count(*) FILTER (WHERE estado='Aprobada') aprobadas,round(avg(nota_final) FILTER (WHERE estado='Aprobada'),2) promedio FROM historial_academico WHERE legajo=$1`,[l])]);
  const s=total.rows[0]; res.json({resumen:{total:Number(s.total),aprobadas:Number(s.aprobadas),avance:Number(s.total)?Math.round(Number(s.aprobadas)*100/Number(s.total)):0,promedio:s.promedio},materias:hist.rows});
} catch(e){next(e);} }

async function asistencias(req,res,next){try { if(!own(req,res))return; const {rows}=await pool.query(`SELECT c.id_comision "idComision",m.nombre_materia "nombreMateria",c.nombre,c.dias_horarios "diasHorarios",count(a.*) clases,count(a.*) FILTER(WHERE a.estado='Presente') presentes,count(a.*) FILTER(WHERE a.estado='Ausente') ausentes,round(100.0*count(a.*) FILTER(WHERE a.estado='Presente')/NULLIF(count(a.*),0),0) porcentaje FROM comision c JOIN materia m ON m.id_materia=c.id_materia LEFT JOIN asistencia a ON a.id_comision=c.id_comision AND a.legajo=$1 WHERE c.id_periodo=(SELECT id_periodo FROM periodo_academico WHERE activo LIMIT 1) GROUP BY c.id_comision,m.nombre_materia,c.nombre,c.dias_horarios`,[req.user.legajo]);res.json(rows);}catch(e){next(e);}}
async function detalleAsistencia(req,res,next){try {const {rows}=await pool.query("SELECT fecha,estado,justificada FROM asistencia WHERE legajo=$1 AND id_comision=$2 ORDER BY fecha DESC",[req.user.legajo,req.params.idComision]);res.json(rows);}catch(e){next(e);}}
async function oferta(req,res,next){try {const {rows}=await pool.query(`SELECT c.id_comision "idComision",m.id_materia "idMateria",m.nombre_materia "nombreMateria",c.nombre,c.dias_horarios "diasHorarios",c.docente,c.cupo_total-COUNT(i.id_inscripcion) FILTER(WHERE i.estado='Confirmada') cupos FROM comision c JOIN materia m ON m.id_materia=c.id_materia LEFT JOIN inscripcion i ON i.id_comision=c.id_comision WHERE c.id_periodo=(SELECT id_periodo FROM periodo_academico WHERE activo LIMIT 1) AND NOT EXISTS (SELECT 1 FROM correlativa co WHERE co.id_materia_principal=m.id_materia AND NOT EXISTS (SELECT 1 FROM historial_academico h WHERE h.legajo=$1 AND h.id_materia=co.id_materia_requerida AND h.estado IN ('Aprobada','Regularizada'))) GROUP BY c.id_comision,m.id_materia,m.nombre_materia,c.nombre,c.dias_horarios,c.docente,c.cupo_total`,[req.user.legajo]);res.json(rows);}catch(e){next(e);}}
async function mesas(req,res,next){try {const {rows}=await pool.query(`SELECT me.id_mesa "idMesa",m.nombre_materia "nombreMateria",me.fecha_hora "fechaHora",me.aula,me.tribunal,me.fecha_limite_baja "fechaLimiteBaja",CASE WHEN EXISTS(SELECT 1 FROM historial_academico h WHERE h.legajo=$1 AND h.id_materia=me.id_materia AND h.estado='Regularizada') THEN 'Regular' ELSE 'Libre' END condicion FROM mesa_examen me JOIN materia m ON m.id_materia=me.id_materia ORDER BY me.fecha_hora`,[req.user.legajo]);res.json(rows);}catch(e){next(e);}}
async function crearCursada(req,res,next){try {const {idComision}=req.body; const {rows}=await pool.query(`SELECT c.id_materia,m.nombre_materia,c.cupo_total-COUNT(i.id_inscripcion) FILTER(WHERE i.estado='Confirmada') cupos FROM comision c JOIN materia m ON m.id_materia=c.id_materia LEFT JOIN inscripcion i ON i.id_comision=c.id_comision WHERE c.id_comision=$1 GROUP BY c.id_materia,m.nombre_materia,c.cupo_total`,[idComision]);if(!rows[0]||Number(rows[0].cupos)<1)return res.status(409).json({error:'No hay cupos disponibles.'});const hash=crypto.randomBytes(12).toString('hex');const r=await pool.query("INSERT INTO inscripcion(legajo,id_materia,id_comision,tipo_instancia,comprobante_hash) VALUES($1,$2,$3,'Cursada',$4) RETURNING id_inscripcion \"idInscripcion\",comprobante_hash \"comprobante\"",[req.user.legajo,rows[0].id_materia,idComision,hash]);res.status(201).json({...r.rows[0],materia:rows[0].nombre_materia});}catch(e){next(e);}}
async function crearFinal(req,res,next){try {const {idMesa}=req.body;const q=await pool.query("SELECT me.id_materia,CASE WHEN EXISTS(SELECT 1 FROM historial_academico h WHERE h.legajo=$1 AND h.id_materia=me.id_materia AND h.estado='Regularizada') THEN 'Regular' ELSE 'Libre' END condicion FROM mesa_examen me WHERE me.id_mesa=$2",[req.user.legajo,idMesa]);if(!q.rows[0])return res.status(404).json({error:'Mesa inexistente.'});const hash=crypto.randomBytes(12).toString('hex');const r=await pool.query("INSERT INTO inscripcion(legajo,id_materia,id_mesa,tipo_instancia,condicion,comprobante_hash) VALUES($1,$2,$3,'Final',$4,$5) RETURNING id_inscripcion \"idInscripcion\",comprobante_hash \"comprobante\"",[req.user.legajo,q.rows[0].id_materia,idMesa,q.rows[0].condicion,hash]);res.status(201).json(r.rows[0]);}catch(e){next(e);}}
async function baja(req,res,next){try {const q=await pool.query(`UPDATE inscripcion i SET estado='Anulada' FROM mesa_examen me WHERE i.id_inscripcion=$1 AND i.legajo=$2 AND i.id_mesa=me.id_mesa AND NOW()<me.fecha_limite_baja AND i.estado='Confirmada' RETURNING i.id_inscripcion`,[req.params.id,req.user.legajo]);if(!q.rowCount)return res.status(409).json({error:'La baja no está disponible para esta inscripción.'});res.json({ok:true});}catch(e){next(e);}}
module.exports={analitico,asistencias,detalleAsistencia,oferta,mesas,crearCursada,crearFinal,baja};
